image: python:3.6-slim

before_script:
  - apt-get update --yes
  - apt-get install gcc

variables:
  BOT_IMAGE: $DOCKERHUB_USER/bot
  COACH_IMAGE: $DOCKERHUB_USER/coach

stages:
  - test style
  # - test stories
  - build requirements
  - build coach
  - build


#############################################################
#################### TEST STYLE #############################
#############################################################
test style:
  image: python:3.7-alpine
  stage: test style
  before_script:
    - pip install flake8
  script:
    - flake8

#############################################################
############### TEST STORIES ################################
#############################################################
# test stories:
#   stage: test stories
#   image: docker
#   tags:
#     - docker
#   services:
#     - docker:dind
#   script:
#     - docker build -f docker/coach.Dockerfile -t $COACH_IMAGE:latest .
#     - docker build -f docker/bot.Dockerfile -t $BOT_IMAGE:latest .
#     - docker run --rm $BOT_IMAGE:latest make test-stories


#############################################################
############### BUILD REQUIREMENTS ##########################
#############################################################
# build requirements:
#   stage: build requirements
#   image: docker
#   tags:
#     - docker
#   services:
#     - docker:dind
#   script:
#     - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#     - cd ./docker
#     - docker build . -f docker/requirements.Dockerfile -t lappis/botrequirements:boilerplate
#     - docker push lappis/botrequirements:boilerplate
#   only:
#     refs:
#       - master
#     changes:
#       - ./requirements.txt
#   environment: homolog


#############################################################
############### BUILD COACH #################################
#############################################################
# build coach:
#   stage: build coach
#   image: docker
#   tags:
#     - docker
#   services:
#     - docker:dind
#   script:
#     - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#     - docker build -f docker/coach.Dockerfile -t $COACH_IMAGE:latest .
#     - docker push $COACH_IMAGE:latest
#   only:
#     - master
#   environment: homolog


#############################################################
############### BUILD BOT ###################################
#############################################################
# build bot:
#   stage: build
#   image: docker
#   tags:
#     - docker
#   services:
#     - docker:dind
#   script:
#     - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#     - docker build -f docker/bot.Dockerfile -t $BOT_IMAGE:latest .
#     - docker push $BOT_IMAGE:latest
#   only:
#     - master
#   environment: homolog
