version: '3'

services:
  # =============================== Coach =================================
  # All the models are trained by this coach.
  coach:
    build:
      context: .
      dockerfile: ./docker/coach.Dockerfile
    volumes:
      - ./bot/models/:/bot/models/
    command: sh -c "make train"


  # ================================= Bot =====================================
  # Generic Rasa bot, used to run console for example.
  bot:
    image: lappis/bot:boilerplate
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    ports:
      - 5004:5004
    depends_on:
      - actions

  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    env_file:
      - env/bot-telegram.env
    volumes:
      - ./bot/actions:/bot/actions
    command: sh -c "make run-actions"

  # ============================ WebChat Bot =================================
  # Specific Rasa bot integrated with WebChat.
  bot-webchat:
      build:
        context: .
        dockerfile: ./docker/bot.Dockerfile
      ports:
        - 5005:5005
      depends_on:
        - actions
      command: sh -c "make webchat"

  # =============================== Analytics =================================
  # Analitics ElasticSearch Stack.
  elasticsearch:
    build:
      context: .
      dockerfile: ./docker/elasticsearch.Dockerfile
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    env_file:
      - env/elasticsearch.env
    volumes:
      - esbackup:/usr/share/elasticsearch/backup
      - ./modules/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data

  # Visualization layer of Analitics Stack.
  kibana:
    build:
      context: .
      dockerfile: ./docker/kibana.Dockerfile
    restart: unless-stopped
    ports:
      - 5601:5601
    env_file:
      - env/kibana.env
    depends_on:
      - elasticsearch

  # =============================== Broker ====================================
  # Custom broker to store Rasa tracker data.
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - ./db/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
    env_file:
      - env/rabbitmq.env

  # Custom broker consumer responsible to store data into ElasticSearch.
  rabbitmq-consumer:
    build:
      context: .
      dockerfile: ./docker/consumer.Dockerfile
    restart: unless-stopped
    volumes:
      - ./modules/rabbitmq/consumer/:/opt/scripts/
    depends_on:
      - rabbitmq
    env_file:
      - env/rabbitmq-consumer.env
    command: python3 /opt/scripts/consume_bot_messages.py

  # ============================ Telegram Bot =================================
  # Specific Rasa bot integrated with Telegram.
  bot_telegram:
      build:
        context: .
        dockerfile: ./docker/bot.Dockerfile
      env_file:
        - env/bot-telegram.env
      ports:
        - 5001:5001
      depends_on:
        - actions
        - database
      volumes:
        - ./bot:/bot
      command: sh -c "make telegram"

  # =============================== Notebooks =================================
  # Rasa lab to enhance hyperparameters.
  notebooks:
    build:
      context: .
      dockerfile: ./docker/notebooks.Dockerfile
    env_file:
      - env/notebooks.env
    volumes:
      - ./modules/notebooks:/work/notebooks
      - ./bot/:/bot/
    ports:
      - 8888:8888
    depends_on:
      - coach

  # =============================== Database =================================
  database:
    container_name: database-alana
    image: mongo:latest
    command: mongod
    volumes:
      - /alana/mongo-alana:/data/db
    ports:
      - 27017:27017

  # =============================== Celery =================================
  celery: &celery
    container_name: celery-alana
    build:
      context: .
      dockerfile: ./docker/celery.Dockerfile
    volumes:
        - ./outputs:/cronjob/home
    env_file:
      - env/bot-telegram.env
    depends_on:
        - database
        - rabbitmq
        - elasticsearch

  celery-beat:    
    <<: *celery
    container_name: celery-beat-alana
    command: ["celery", "-A", "tasks", "beat", 
              "--app", "tasks.celeryapp", "-l", "info"]
  
  celery-worker:
    <<: *celery
    container_name: celery-worker-alana
    depends_on:
      - celery-beat
    command: ["celery", "-A", "tasks", "worker",
              "--app", "tasks.celeryapp", "-l", "info"]

volumes:
  notebook_models:
  mongo_data:
  rabbit_data:
  esbackup:
  esdata:
    driver: local
